# Generated by Django 6.0 on 2026-01-04 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Stát s tímto názvem již existuje.'}, max_length=100, unique=True, verbose_name='Název')),
            ],
            options={
                'verbose_name': 'Stát',
                'verbose_name_plural': 'Státy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Název')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Sport s tímto názvem již existuje.'}, max_length=100, unique=True, verbose_name='Název')),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sporty',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Název')),
                ('zip_code', models.CharField(max_length=10, verbose_name='PSČ')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='viewer.country', verbose_name='Název')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='viewer.region', verbose_name='Kraj')),
            ],
            options={
                'verbose_name': 'Město',
                'verbose_name_plural': 'Města',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název')),
                ('description', models.TextField(verbose_name='Popis')),
                ('address', models.TextField(verbose_name='Adresa')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='viewer.city', verbose_name='Město')),
            ],
            options={
                'verbose_name': 'Lokace',
                'verbose_name_plural': 'Lokace',
                'ordering': ['city__name', 'name'],
                'unique_together': {('name', 'address')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('start_date_time', models.DateTimeField(verbose_name='Datum a čas začátku')),
                ('end_date_time', models.DateTimeField(verbose_name='Datum a čas konce')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Obrázek')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kapacita')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum upravení')),
                ('owner_of_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_events', to=settings.AUTH_USER_MODEL, verbose_name='Majitel události')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='viewer.location', verbose_name='Lokace')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='viewer.sport', verbose_name='Sport')),
            ],
            options={
                'verbose_name': 'Událost',
                'verbose_name_plural': 'Události',
            },
        ),
    ]
