# Generated by Django 6.0 on 2026-01-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(error_messages={'unique': 'Stát s tímto názvem již existuje.'}, max_length=100, unique=True, verbose_name='Název země'),
        ),
    ]
